"""empty message

Revision ID: 2cdf3ea4b0c5
Revises: b3c4d5e6f7a8
Create Date: 2026-05-25 00:52:18.493783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cdf3ea4b0c5'
down_revision: Union[str, None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('airline', sa.String(), server_default=sa.text("'flyone'"), nullable=False))
    op.create_index(op.f('ix_flights_airline'), 'flights', ['airline'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flights_airline'), table_name='flights')
    op.drop_column('flights', 'airline')
    # ### end Alembic commands ###
