"""empty message

Revision ID: 827618db3e02
Revises: cb8f8518e6fe
Create Date: 2024-12-29 02:07:26.342548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '827618db3e02'
down_revision: Union[str, None] = 'cb8f8518e6fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src', sa.String(length=3), nullable=False),
    sa.Column('dst', sa.String(length=3), nullable=False),
    sa.Column('travel_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('src', 'dst', 'travel_date', name='uix_src_dst_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flights')
    # ### end Alembic commands ###
