"""empty message

Revision ID: b7464f009125
Revises: 16a547ce6c45
Create Date: 2026-05-30 16:37:18.636217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7464f009125'
down_revision: Union[str, None] = '16a547ce6c45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('currency', sa.String(), server_default=sa.text("'EUR'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flights', 'currency')
    # ### end Alembic commands ###
