"""empty message

Revision ID: ce58ffc9544d
Revises: 7e1ba3d50b55
Create Date: 2024-10-14 00:36:33.184985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce58ffc9544d'
down_revision: Union[str, None] = '7e1ba3d50b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('directions', 'msg_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directions', sa.Column('msg_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
