"""empty message

Revision ID: fef2b7dadfb0
Revises: 9da5c618b417
Create Date: 2024-10-19 11:08:28.228740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fef2b7dadfb0'
down_revision: Union[str, None] = '9da5c618b417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('chats',
                  sa.Column('schedule', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))

    # Update existing rows, setting schedule to False for all existing records
    op.execute('UPDATE chats SET schedule = FALSE')

    # Remove the default now that the data is updated (if not needed in the database level)
    op.alter_column('chats', 'schedule', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'schedule')
    # ### end Alembic commands ###
